version: '3'
services:
  coordinator:
    image: stellar-coordinator:latest
    ports:
      - "8080:8080"
    networks:
      - stellar
  redis:
    image: redis:4.0.6-alpine
    container_name: redis
    networks:
      - stellar
networks:
  stellar:
